### ISSUE TITLE
Warning: Variable 'net' originally saved as a dlnetwork cannot be instantiated as an object and will be read in as a uint32.

### ISSUE THREAD

**Issue by YueSun0609** [matlab-deep-learning/Lidar-object-detection-using-complex-yolov4#1]
Then net can't be used as an object, it becomes:
net =

  6×1 uint32 column vector

   3707764736
            2
            1
            1
            1
           15

**Comment by vancha-MW** [comment]
Can you give more information about what MATLAB version you are working on? 
Also for the demo to work, you would require license for the Lidar and Deep Learning toolbox.

**Comment by YueSun0609** [comment]
> 

Hi Vancha-MW, I use the lateset version, which should be R2023a. I just have the license for Matlab but not sure if I also have a liscense for Lidar toolbox since I was never asked to provide a licence during the whole process. Is that the issue?

**Comment by vancha-MW** [comment]
Hi YueSun0609, 

Yes, you would require license for Deep Learning toolbox and Lidar toolbox to run the demo. You can run the following command to get license status,

`license('inuse')`

**Comment by YueSun0609** [comment]
> Hi YueSun0609,
> 
> Yes, you would require license for Deep Learning toolbox and Lidar toolbox to run the demo. You can run the following command to get license status,
> 
> `license('inuse')`

Yes, I solved the problem after I got a license. Thank you so much!
